services: 
  api:
    build: .
    #port format = <port on localhost>:<port on container>
    ports:
      - "8000:8000"
    
    env_file:
      - .env
    depends_on:
      - qdrant
    volumes:
    - ~/.aws:/root/.aws:ro

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
  
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  qdrant_storage: {}