"""auto-Create images Table

Revision ID: 09b4abfe8457
Revises: 580b0c337a7e
Create Date: 2025-05-16 15:39:33.406826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b4abfe8457'
down_revision: Union[str, None] = '580b0c337a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('adventure_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventures.adventure_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
