"""auto-add captions to images Table

Revision ID: 6f23f27fecde
Revises: 09b4abfe8457
Create Date: 2025-05-16 15:40:47.807152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f23f27fecde'
down_revision: Union[str, None] = '09b4abfe8457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('caption', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'caption')
    # ### end Alembic commands ###
