name: Build code

on:
  push:
    branches: ["main"] #only on push to main branch
  pull_request:
    branches: ["main"]

jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: say hi
        run: echo "hello world"
