name: Build code

on:
  push:
    branches: ["main"] #only on push to main branch
  pull_request:
    branches: ["main"]

jobs:
  job1:
    environment: Testing
    env: 
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MIN: ${{secrets.ACCESS_TOKEN_EXPIRE_MIN}}

    runs-on: ubuntu-latest
    steps:

      - name: pulling git repo
        uses: actions/checkout@v4

      - name: install python version 3.13.2
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: update pip
        run: python -m pip install --upgrade pip

      - name: install all dependencies
        run: pip install -r requirments.txt

      - name: test with pytest
        run: |
          pip install pytest
          pytest
