name: Build code

on:
  push:
    branches: ["main"] #only on push to main branch
  pull_request:
    branches: ["main"]

jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:

      - name: pulling git repo
        uses: actions/checkout@v4

      - name: install python version 3.13.2
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: update pip
        run: python -m pip install --upgrade pip

      - name: install all dependencies
        run: pip install -r requirments.txt

      - name: test with pytest
        run: |
          pip install pytest
          pip freeze > requirments.txt
          pytest
